import { TestBank } from "@/types";

export const DEMO_TESTS: TestBank[] = [
  {
    id: "demo_1",
    testName: "CIL Mock Set 1 - General Awareness",
    duration: 30,
    createdAt: Date.now(),
    questions: [
      {
        id: 1,
        section: "General Awareness",
        difficulty: "easy",
        question: "Who is known as the Missile Man of India?",
        options: {
          A: "Vikram Sarabhai",
          B: "Homi Bhabha",
          C: "A.P.J. Abdul Kalam",
          D: "Satish Dhawan",
        },
        correctAnswer: "C",
        explanation: "A.P.J. Abdul Kalam is known as the Missile Man of India for his contributions to India's missile program.",
      },
      {
        id: 2,
        section: "General Awareness",
        difficulty: "easy",
        question: "What is the capital of Australia?",
        options: {
          A: "Sydney",
          B: "Melbourne",
          C: "Canberra",
          D: "Brisbane",
        },
        correctAnswer: "C",
        explanation: "Canberra is the capital city of Australia, located in the Australian Capital Territory.",
      },
      {
        id: 3,
        section: "General Knowledge",
        difficulty: "medium",
        question: "Which planet is known as the Red Planet?",
        options: {
          A: "Venus",
          B: "Mars",
          C: "Jupiter",
          D: "Saturn",
        },
        correctAnswer: "B",
        explanation: "Mars is known as the Red Planet due to the presence of iron oxide on its surface.",
      },
      {
        id: 4,
        section: "General Awareness",
        difficulty: "medium",
        question: "Who wrote the Indian Constitution?",
        options: {
          A: "Jawaharlal Nehru",
          B: "Mahatma Gandhi",
          C: "Dr. B.R. Ambedkar",
          D: "Sardar Vallabhbhai Patel",
        },
        correctAnswer: "C",
        explanation: "Dr. B.R. Ambedkar was the principal architect of the Indian Constitution and the chairman of the Drafting Committee.",
      },
      {
        id: 5,
        section: "General Knowledge",
        difficulty: "hard",
        question: "What is the atomic number of Gold?",
        options: {
          A: "79",
          B: "80",
          C: "81",
          D: "78",
        },
        correctAnswer: "A",
        explanation: "Gold (Au) has an atomic number of 79, making it a precious metal in the periodic table.",
      },
      {
        id: 6,
        section: "General Awareness",
        difficulty: "medium",
        question: "Which country is known as the Land of the Rising Sun?",
        options: {
          A: "China",
          B: "Japan",
          C: "Korea",
          D: "Vietnam",
        },
        correctAnswer: "B",
        explanation: "Japan is known as the Land of the Rising Sun because it is located to the east of Asia, where the sun rises.",
      },
      {
        id: 7,
        section: "General Knowledge",
        difficulty: "easy",
        question: "What is the largest ocean on Earth?",
        options: {
          A: "Atlantic Ocean",
          B: "Indian Ocean",
          C: "Arctic Ocean",
          D: "Pacific Ocean",
        },
        correctAnswer: "D",
        explanation: "The Pacific Ocean is the largest and deepest ocean on Earth, covering about 46% of the ocean surface.",
      },
      {
        id: 8,
        section: "General Awareness",
        difficulty: "medium",
        question: "Who is the founder of Microsoft?",
        options: {
          A: "Steve Jobs",
          B: "Bill Gates",
          C: "Mark Zuckerberg",
          D: "Elon Musk",
        },
        correctAnswer: "B",
        explanation: "Bill Gates co-founded Microsoft with Paul Allen in 1975, revolutionizing personal computing.",
      },
      {
        id: 9,
        section: "General Knowledge",
        difficulty: "hard",
        question: "What is the speed of light in vacuum?",
        options: {
          A: "3 × 10^7 m/s",
          B: "3 × 10^8 m/s",
          C: "3 × 10^9 m/s",
          D: "3 × 10^6 m/s",
        },
        correctAnswer: "B",
        explanation: "The speed of light in vacuum is approximately 3 × 10^8 meters per second (299,792,458 m/s).",
      },
      {
        id: 10,
        section: "General Awareness",
        difficulty: "easy",
        question: "What is the currency of India?",
        options: {
          A: "Dollar",
          B: "Euro",
          C: "Indian Rupee",
          D: "Pound",
        },
        correctAnswer: "C",
        explanation: "The Indian Rupee (₹) is the official currency of the Republic of India.",
      },
      {
        id: 11,
        section: "General Knowledge",
        difficulty: "medium",
        question: "Which element has the symbol 'Fe' on the periodic table?",
        options: {
          A: "Fluorine",
          B: "Fermium",
          C: "Iron",
          D: "Francium",
        },
        correctAnswer: "C",
        explanation: "Iron (Fe) is a chemical element with atomic number 26, essential for human health and industrial applications.",
      },
      {
        id: 12,
        section: "General Awareness",
        difficulty: "hard",
        question: "What is the main component of the sun?",
        options: {
          A: "Oxygen",
          B: "Nitrogen",
          C: "Hydrogen",
          D: "Carbon",
        },
        correctAnswer: "C",
        explanation: "Hydrogen makes up about 73% of the Sun's mass and is the fuel for the Sun's fusion reactions.",
      },
      {
        id: 13,
        section: "General Knowledge",
        difficulty: "easy",
        question: "How many continents are there?",
        options: {
          A: "5",
          B: "6",
          C: "7",
          D: "8",
        },
        correctAnswer: "C",
        explanation: "There are 7 continents: Africa, Antarctica, Asia, Europe, North America, Oceania, and South America.",
      },
      {
        id: 14,
        section: "General Awareness",
        difficulty: "medium",
        question: "Who won the Nobel Prize in Physics in 2020?",
        options: {
          A: "Roger Penrose, Reinhard Genzel, Andrea Ghez",
          B: "Peter Higgs",
          C: "Stephen Hawking",
          D: "Albert Einstein",
        },
        correctAnswer: "A",
        explanation: "Roger Penrose, Reinhard Genzel, and Andrea Ghez won the 2020 Nobel Prize in Physics for discoveries in black hole research.",
      },
      {
        id: 15,
        section: "General Knowledge",
        difficulty: "hard",
        question: "What is the pH value of pure water at 25°C?",
        options: {
          A: "6",
          B: "7",
          C: "8",
          D: "5",
        },
        correctAnswer: "B",
        explanation: "Pure water at 25°C has a pH value of exactly 7, making it neutral on the pH scale.",
      },
    ],
  },
];
